04/11/2020 09:03:05 PM Performing 16800 experiments in 50400 minutes (max.)
04/11/2020 09:03:52 PM Window and sample: /almac/ignacio/results_srl_env/wsize-8/sample-10
04/11/2020 09:03:52 PM Parameters test 0/580 (0.0 %%): {'bias': 0.0, 'hitmiss': 1.0, 'bw': 2.0, 'density': 'gausset', 'ngrams': (2, 4)}
04/11/2020 09:03:53 PM Computing probabilities of random sets for 2856 steps.
04/11/2020 09:10:30 PM Computing probabilities of random sets for 2856 steps.
04/11/2020 09:17:06 PM Parameters test 1/580 (0.2 %%): {'bias': 5.0, 'hitmiss': 0.0, 'bw': 2.0, 'density': 'gausset', 'ngrams': (2, 4)}
04/11/2020 09:17:06 PM Computing probabilities of random sets for 2856 steps.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/almac/ignacio/semanticrl/srl_vs_rdn.py", line 257, in compute_set_probability
    _ = np.apply_along_axis(np.random.shuffle, 1, dupst)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 363, in apply_along_axis
    axis = normalize_axis_index(axis, nd)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_loop.py", line 90, in <module>
    main()
  File "test_loop.py", line 86, in main
    test.fit(**param)
  File "/almac/ignacio/semanticrl/srl_vs_rdn.py", line 430, in fit
    ngramr=ngrams, n_hit_miss=n_hit_miss, bias=bias)
  File "/almac/ignacio/semanticrl/srl_vs_rdn.py", line 334, in compute_mi_steps
    for A_k in A_tau)
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/almac/ignacio/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
04/11/2020 09:22:48 PM Performing 16800 experiments in 50400 minutes (max.)
04/11/2020 09:23:35 PM Window and sample: /almac/ignacio/results_srl_env/wsize-8/sample-10
04/11/2020 09:23:35 PM Parameters test 0/584 (0.0 %%): {'bias': 5.0, 'hitmiss': 1.0, 'bw': 3.0, 'density': 'gausset', 'ngrams': (2, 4)}
04/11/2020 09:23:36 PM Computing probabilities of random sets for 2856 steps.
04/11/2020 09:30:27 PM Computing probabilities of random sets for 2856 steps.
04/11/2020 09:37:09 PM Parameters test 1/584 (0.2 %%): {'bias': 5.0, 'hitmiss': 1.0, 'bw': 2.0, 'density': 'gausset', 'ngrams': (1, 2)}
04/11/2020 09:37:09 PM Computing probabilities of random sets for 2856 steps.
